sudo: required
services:
  - docker

before_install:
  - docker build -t merodocker/fullstack-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true merodocker/fullstack-app npm test -- --coverage

after_success:
  - docker build -t merodocker/multi-client ./client
  - docker build -t merodocker/multi-nginx ./nginx
  - docker build -t merodocker/multi-server ./server
  # Log in to the docker CLI
before_deploy:
  - docker ps -all
  - echo "hello i am without if"
  if: branch = master
  - echo " hello i am after if statement"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push merodocker/multi-client
  - docker push merodocker/multi-nginx
  - docker push merodocker/multi-server

deploy:
  artifact: Dockerrun.aws.json
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-198087152377
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
