version: '2'
services:
  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  frontend:
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
  backend:
    build: 
      context: ./backend/customer-api
      dockerfile: dev.Dockerfile
    
    volumes:
      - ./backend/customer-api:/app
      - /app/node_modules
    