version: '2'
services:
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
  backend:
    build: 
      context: ./backend/customer-api
      dockerfile: dev.Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend/customer-api:/app
      - /app/node_modules
    